[package]
name = "rsgen"
version = "0.3.29"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/sidneywang/genco"
homepage = "https://github.com/sidneywang/genco"
documentation = "https://docs.rs/genco"
description = """
Even simpler code generation for Rust.
"""
